### PR TITLE
CorrDiff integration: Make cftime test optional

### PR DESCRIPTION
**Pull request by mnabian**
# Modulus Pull Request

## Description

Closes https://github.com/NVIDIA/modulus/issues/319

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [ ] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [x] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Review by ktangsali — APPROVED** [review]
Thanks for the quick fix on this bug @mnabian! Let's just confirm that only this library needed such handling (because I saw 3 packages added in this commit [here](https://github.com/NVIDIA/modulus/commit/13d8853674fb637f42478f63b42486c5d699f805) and then it should be ready to go.

**Review by NickGeneva — APPROVED** [review]

**Comment by mnabian** [comment]
> Thanks for the quick fix on this bug @mnabian! Let's just confirm that only this library needed such handling (because I saw 3 packages added in this commit [here](https://github.com/NVIDIA/modulus/commit/13d8853674fb637f42478f63b42486c5d699f805)) and then it should be ready to go.

Thanks. Verified this is the only package.

**Pull request merged**
