### PR TITLE
CorrDiff: Fix scaling bug in deterministic sampler

### PR DESCRIPTION
**Pull request by mnabian**
# Modulus Pull Request

Closes https://github.com/NVIDIA/modulus/issues/418

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Review by nbren12 — APPROVED** [review]
LGTM. Thanks for the quick fix.

**Review by MortezaMardani — APPROVED** [review]

**Pull request merged**
