### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by mnabian**
# Modulus Pull Request

## Checklist

- [ ] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.
- [ ] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Comment by mnabian** [comment]
Hi @Alexey-Kamenev , I updated the ci image based on these changes, and now SFNO test gives this error:
```
=========================== short test summary info ============================
FAILED test/models/test_sfno.py::test_sfno_forward[cuda:0] - KeyError: 'No model is registered under the name SFNO'
FAILED test/models/test_sfno.py::test_sfno_forward[cpu] - KeyError: 'No model is registered under the name SFNO'
FAILED test/models/test_sfno.py::test_sfno_checkpoint[cuda:0] - KeyError: 'No model is registered under the name SFNO'
FAILED test/models/test_sfno.py::test_sfno_checkpoint[cpu] - KeyError: 'No model is registered under the name SFNO'
====== 4 failed, 783 passed, 52 skipped, 61 warnings in 713.67s (0:11:53) ======
```
Do you know why this is happening?

**Review by Alexey-Kamenev — APPROVED** [review]
LGTM

**Review by ktangsali — APPROVED** [review]
Has the CI image been updated?

**Comment by mnabian** [comment]
> Has the CI image been updated?

Yes, image tag 0.30

**Pull request merged**
