### PR TITLE
SFNO update - part 2

### PR DESCRIPTION
**Pull request by mnabian**
# Modulus Pull Request

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Review by daviddpruitt — APPROVED** [review]

**Review by Alexey-Kamenev — APPROVED** [review]
Thank you!

**Comment by mnabian** [comment]
Git hash (Makani): 0cd7032135ef1fd49fa8809abbe7f7ca7fb30cb5

**Pull request merged**
