### PR TITLE
add random weight factorization

### LINKED ISSUE #159: 🚀[FEA]: Random weight factorization for improving the training of MLPs
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem you would like to solve.

A simple drop-in replacement for parameterizing and initializing conventional linear layers that accelerates and improves their training.  More details can be found in https://arxiv.org/abs/2210.01274.

### Describe any alternatives you have considered

_No response_

### PR DESCRIPTION
**Pull request by sifanw094**
# Modulus Pull Request

Closes #159 

## Description

#

A simple drop-in replacement for parameterizing and initializing conventional linear layers that accelerates and improves their training. 

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [ ] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [x] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Comment by sifanw094** [comment]
blossom-ci

**Comment by mnabian** [comment]
@sifanw094 pytest fails. Please add `WeightFactLinear` import to `models/layers/__init__.py`

**Comment by sifanw094** [comment]
> @sifanw094 pytest fails. Please add `WeightFactLinear` import to `models/layers/__init__.py`



> @sifanw094 pytest fails. Please add `WeightFactLinear` import to `models/layers/__init__.py`

Thanks for pointing this out, I have fixed it.

**Comment by mnabian** [comment]
@sifanw094 `test_fully_connected.py` still fails. Please fix it.

**Comment by sifanw094** [comment]
> @sifanw094 `test_fully_connected.py` still fails. Please fix it.

Sorry for any inconvenience it may cause. I have fixed it and passed pytest on my side.

**Review by mnabian — APPROVED** [review]

**Review by ktangsali — APPROVED** [review]
Looks good! Thanks for adding this

**Pull request merged**
