### PR TITLE
Fix Timezone to UTC in Datapipes and Cosine Zenith

### PR DESCRIPTION
**Pull request by dallasfoster**
# Modulus Pull Request

## Description
This PR fixes timezones in the ERA5 datapipes and in the related cosine zenith utilities. There was a discrepancy because of this that caused a `+3600` to appear to be correct, but was likely an artifact due to improperly set time zones.

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Review by mnabian — APPROVED** [review]
Based on the results provided offline, the changes here look good. Approving

**Comment by jleinonen** [comment]
This looks good, I'm approving the fix as well.

**Pull request merged**
