### PR TITLE
Remove MLFlow from deployment image

### PR DESCRIPTION
**Pull request by ktangsali**
# Modulus Pull Request

## Description
MLFlow often has several CVEs that makes it difficult to ship containers as the patches sometimes take time to become available. This removes MLFlow from the deployment image for the OSS container and throws an import error if `mlflow` install is not found. 

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Review by NickGeneva — APPROVED** [review]

**Comment by mnabian** [comment]
@ktangsali I think we should either update the README of the recipes that are using mlflow, or add a requirements.txt with mlflow.

**Comment by ktangsali** [comment]
> @ktangsali I think we should either update the README of the recipes that are using mlflow, or add a requirements.txt with mlflow.

Good point @mnabian , I have added a requirements.txt for all examples using the `initialize_mlflow` util from Modulus.

**Pull request merged**
