### PR TITLE
Update dali dependency to a cuda 12 compatible version

### PR DESCRIPTION
**Pull request by ktangsali**
# Modulus Pull Request

## Description
Closes https://github.com/NVIDIA/modulus/issues/493

Tested the change by executing pytests in a blank conda environment with modulus source install.

The Modulus container was already using a CUDA 12 compatible Dali version so no changes required to the Dockerfile. 

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [x] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Comment by azrael417** [comment]
Looks good to me, I think this one is a no-brainer. Any objections?

**Review by azrael417 — APPROVED** [review]
Looks good to me. As you said, modulus was already using DALI for CUDA 12.

**Review by NickGeneva — APPROVED** [review]

**Pull request merged**
