### PR TITLE
CorrDiff: Adding NVTX markers and removing redundant regression model inference

### PR DESCRIPTION
**Pull request by akshaysubr**
# Modulus Pull Request

## Description

This PR adds:
1. CUDA event based timing
2. NVTX markers to aid profiling
3. Regression model inference optimization by removing redundant compute

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

## Dependencies
[nvtx](https://github.com/NVIDIA/NVTX/tree/dev/python) python library

### CODE REVIEW

**Comment by mnabian** [comment]
@akshaysubr please merge to `rc`

**Review by MortezaMardani — APPROVED** [review]

**Review by mnabian — APPROVED** [review]
LGTM

**Pull request merged**
