### PR TITLE
[FEA] Update the citation text

### PR DESCRIPTION
**Pull request by mnabian**
# Modulus Pull Request

This PR updates the citation text. Here's how the BibTeX is compiled in different formats:

Harvard:
Modulus Contributors. (2023). NVIDIA Modulus: An Open-source framework for building, training, and fine-tuning deep learning models for science and engineering. https://github.com/NVIDIA/modulus

IEEE:
Modulus Contributors, NVIDIA Modulus: An Open-source framework for building, training, and fine-tuning deep learning models for science and engineering. 2023. [Online]. Available: https://github.com/NVIDIA/modulus

APA:
Modulus Contributors. (2023). NVIDIA Modulus: An Open-source framework for building, training, and fine-tuning deep learning models for science and engineering. https://github.com/NVIDIA/modulus

MLA:
Modulus Contributors. NVIDIA Modulus: An Open-Source Framework for Building, Training, and Fine-Tuning Deep Learning Models for Science and Engineering. 2023, https://github.com/NVIDIA/modulus.

Date is set to the first Alpha release of the Modulus-Core.

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [ ] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Review by ram-cherukuri — APPROVED** [review]
Looks good to me Mohammad. I see subtle differences but dont have a strong opinion. This looks good to go from my side.

**Comment by RishikeshRanade** [comment]
Should we keep the title more general because Modulus can potentially offer features in addition to to building, training and fine tuning of models? For example: "Modulus: An open-source framework for physics based deep learning in science and engineering."

**Comment by ram-cherukuri** [comment]
Yes I like the wording Rishi.

**Comment by mnabian** [comment]
> Should we keep the title more general because Modulus can potentially offer features in addition to to building, training and fine tuning of models? For example: "Modulus: An open-source framework for physics based deep learning in science and engineering."

Updated to your suggested text

**Review by RishikeshRanade — APPROVED** [review]

**Pull request merged**
