### PR TITLE
Fix license tests

### LINKED ISSUE #317: 🐛[BUG]: License test from pre-commit also scans for files that are in .gitignore
### Version

0.4.0

### On which installation method(s) does this occur?

Source

### Describe the issue

Currently the license test from `pre-commit` does not ignore the files from `.gitignore`, catching license issues even on non-committed files. The `pre-commit` stage of `license` should be integrated with `.gitignore` similar to other pre-commit checks. 

### Minimum reproducible example

_No response_

### Relevant log output

_No response_

### Environment details

_No response_

### PR DESCRIPTION
**Pull request by ktangsali**
# Modulus Pull Request

## Description
Closes #317, #178  and also updates copyright year. 

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [ ] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [x] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Comment by NickGeneva** [comment]
Wait! if we are doing this can we also add SPDX tags?

```
# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
```

I updated this in earth2mip prior to oss.

@mnabian I think you mentioned doing this once?

**Comment by NickGeneva** [comment]
*Blows dust off*

https://github.com/NVIDIA/modulus/issues/178

**Comment by mnabian** [comment]
> Wait! if we are doing this can we also add SPDX tags?
> 
> ```
> # SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES.
> # SPDX-FileCopyrightText: All rights reserved.
> # SPDX-License-Identifier: Apache-2.0
> ```
> 
> I updated this in earth2mip prior to oss.
> 
> @mnabian I think you mentioned doing this once?

Yes, I think we should also take care of this in this PR.

**Comment by mnabian** [comment]
@ktangsali could you please change the year from `2024` to `2023-2024`?

**Review by NickGeneva — APPROVED** [review]

**Review by mnabian — APPROVED** [review]

**Pull request merged**
