### PR TITLE
regression or diffusion only inference

### PR DESCRIPTION
**Pull request by mnabian**
# Modulus Pull Request

Closes https://github.com/NVIDIA/modulus/issues/392

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [x] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Review by nbren12 — APPROVED** [review]
LGTM. Nice to have flags for this.

Are there integration tests of generate.py against real data? Would be nice to have some more coverage of this script.

**Review by yairchn — APPROVED** [review]
LGTM! 
I think `image_mean` could probably called `image_reg`  as the mean might be confusing as it is not exactly the mean of the diffusion but that semantic

**Pull request merged**
