### PR TITLE
CorrDiff: Remove extra call to training_loop

### PR DESCRIPTION
**Pull request by simonbyrne**
# Modulus Pull Request

## Description
When I ran the training example I got the following error at the end:
```
Traceback (most recent call last):
  File "/code/modulus/examples/generative/corrdiff/train.py", line 335, in main
    training_loop.training_loop(
TypeError: training_loop() missing 3 required positional arguments: 'dataset_iterator', 'validation_dataset', and 'validation_dataset_iterator'
```
The problem appears to be that `training_loop` is called twice in a nested fashion. Since the error is only thrown on the outside call after the first call completes, the error is only raised after the training has already completed (which is why this probably wasn't noticed earlier).

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.
- [ ] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Comment by simonbyrne** [comment]
@mnabian any thoughts/comments?

**Comment by mnabian** [comment]
This is very surprising to me! It was added here: https://github.com/NVIDIA/modulus/commit/1658a43ead87b7466c510be6fd638919bd842bb1#diff-6561b5f6860b33223b323345d5b61da97b7a1b5877d1aa53cc3a63af12399e08L305
@jleinonen was this change intentional?

**Comment by jleinonen** [comment]
Yeah, I noticed this recently too. I don't know how this redundant call got there. I guess it was never caught since it's the last line of the script which avoids the error...

Anyway, LGTM!

**Review by jleinonen — APPROVED** [review]

**Review by mnabian — APPROVED** [review]

**Pull request merged**
