### PR TITLE
[fix] Fix for dlwp_healpix dataloader not subsetting channels correctly

### PR DESCRIPTION
**Pull request by daviddpruitt**
# Modulus Pull Request

## Description
Fixes a bug where the dlwp_healpix dataloader uses a prebuilt dataset with more channels than used by the model. This fix adds channel selection so only the necessary channels are loaded.

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [x] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Review by yairchn — APPROVED** [review]
LGTM

**Comment by mnabian** [comment]
@daviddpruitt is this ready to be merged?

**Comment by daviddpruitt** [comment]
> @daviddpruitt is this ready to be merged?

@mnabian Should be good to go.

**Review by akshaysubr — APPROVED** [review]
Tested this and fixes the stated issue.

**Pull request merged**
