### PR TITLE
fix editable install

### PR DESCRIPTION
**Pull request by mnabian**
# Modulus Pull Request
Fixing editable install of Modulus

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is
up to date with these changes.

### CODE REVIEW

**Review by NickGeneva — DISMISSED** [review]

**Comment by loliverhennigh** [comment]
OOOhhh, so this was what caused the issue?

**Review by loliverhennigh — APPROVED** [review]
Looks great!

**Review by NickGeneva — APPROVED** [review]

**Pull request merged**
