### PR TITLE
Denoising diffusion tutorial

### PR DESCRIPTION
**Pull request by mnabian**
# Modulus Pull Request

## Description

Denoising diffusion tutorial
Preview: https://github.com/mnabian/modulus/blob/fea-ext-diffusion_docs/examples/generative/diffusion/README.md

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [x] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Review by Alexey-Kamenev — APPROVED** [review]
Looks great, thank you!

**Review by ktangsali — APPROVED** [review]
Looks good to me. Very well written tutorial! Added a minor suggestion regarding naming of certain files.

**Pull request merged**
