### PR TITLE
Fixed file permissions and updated entry points configuration.

### PR DESCRIPTION
**Pull request by Alexey-Kamenev**
# Modulus Pull Request

## Description
* Fixed file permissions - removed erroneous "execute" permission.
* Removed setup.py considered deprecated, moved entry points to pyproject.toml.
* Replaced usage of deprecated pkg_resources with importlib.metadata.

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.
- [ ] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Review by loliverhennigh — APPROVED** [review]
This all looks good to me

**Review by ktangsali — APPROVED** [review]

**Pull request merged**
