### PR TITLE
Integrating Sym with Core: Network Architecture Layers

### PR DESCRIPTION
**Pull request by mnabian**
# Modulus Pull Request

## Description

Closes https://github.com/NVIDIA/modulus/issues/167

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [x] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Comment by ktangsali** [comment]
Quick comment - we should probably also include tests for these layers

**Comment by loliverhennigh** [comment]
This is just a cp from Sym right? Looking through the models I don't see anything wrong.

**Review by loliverhennigh — APPROVED** [review]

**Comment by mnabian** [comment]
> Quick comment - we should probably also include tests for these layers

Thanks for the comment. I added unit tests

**Review by ktangsali — APPROVED** [review]
Thanks for adding the tests! Rest looks good. Please merge after CI passes. Thanks.

**Pull request merged**
