### PR TITLE
Fix diffusion example imports.

### PR DESCRIPTION
**Pull request by Alexey-Kamenev**
# Modulus Pull Request

## Description
Updated diffusion example imports.

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [ ] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Review by mnabian — APPROVED** [review]
LGTM. Please change the target branch to rc.

**Review by ktangsali — APPROVED** [review]

**Pull request merged**
