### PR TITLE
Use config file for validation dataset options

### PR DESCRIPTION
**Pull request by jleinonen**
# Modulus Pull Request

## Description

This PR improves the configurability of the validation dataset introduced in https://github.com/NVIDIA/modulus/pull/413:
- The validation dataset is now configured under the `validation_dataset` section of the config file. The validation dataset inherits the config options of the training dataset, except where overridden by `validation_dataset`.
- Remove some hardcoded assumptions about the training dataset. These are replaced by the setup using the config file or moved into the dataset code in `cwb.py`.

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [ ] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Review by yairchn — APPROVED** [review]
looks good to me, please test a small train with train_test_split=True before merging

**Comment by yairchn** [comment]
please test a small train with `train_test_split=True` before merging

**Review by mnabian — APPROVED** [review]
LGTM

**Pull request merged**
