### PR TITLE
Fixed missing logging function export

### LINKED ISSUE #699: 🐛[BUG]: Transolver MLFlow function not exported
### Version

master

### On which installation method(s) does this occur?

Pip

### Describe the issue

The new transolver model added in #591 accesses a logging function in the example code not exported in the __init__, namely

https://github.com/NVIDIA/modulus/blob/89fae509cfabf70c4d441c808d4cc9bac3c84fc9/modulus/launch/logging/mlflow.py#L42

### Minimum reproducible example

Just run the example in the repo

https://github.com/NVIDIA/modulus/blob/89fae509cfabf70c4d441c808d4cc9bac3c84fc9/examples/cfd/darcy_transolver/train_transolver_darcy.py

### Relevant log output

Traceback (most recent call last):
    File "/home/alexk101/Documents/Research/phd/projects/modulus/examples/cfd/darcy_transolver/train_transolver.py", line 25, in <module>
        from modulus.launch.logging import PythonLogger, LaunchLogger, initialize_mlflow
ImportError: cannot import name 'initialize_mlflow' from 'modulus.launch.logging'

### Environment details

Bare metal

### PR DESCRIPTION
**Pull request by alexk101**
# Modulus Pull Request

## Description
Fixes #699 

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [x] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

## Dependencies

n/a

### CODE REVIEW

**Review by mnabian — APPROVED** [review]
LGTM

**Comment by mnabian** [comment]
Ruff failed. Please use pre-commit.

**Comment by alexk101** [comment]
Sorry about that. Should be good now.

**Pull request merged**
