### PR TITLE
[Enh] [CorrDiff] Support rectangular regions in CorrDiff

### PR DESCRIPTION
**Pull request by daviddpruitt**
# Modulus Pull Request

## Description
Add rectangular image support to full domain and patch-based training and inference. Support for 2d image sizes is added to SongUNet, Unet, and ResLoss. If a single dimension is given a square region is assumed retaining the original functionality.

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Review by mnabian — APPROVED** [review]
LGTM. Thanks!

**Review by akshaysubr — APPROVED** [review]

**Pull request merged**
