### PR TITLE
Docs update 0.7.0

### PR DESCRIPTION
**Pull request by ktangsali**
# Modulus Pull Request

## Description
Update docs for 0.7.0 release. 

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [ ] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

### CODE REVIEW

**Comment by ktangsali** [comment]
Duplicate commits seen due to pushes made to RC. Will use "Squash and merge"

**Review by NickGeneva — APPROVED** [review]

**Review by mnabian — APPROVED** [review]

**Pull request merged**
