### PR TITLE
Version update 0.2.0

### PR DESCRIPTION
**Pull request by ktangsali**
# Modulus Pull Request

## Description
Updates the version

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is
up to date with these changes.

### CODE REVIEW

**Comment by akshaysubr** [comment]
@ktangsali Shouldn't this MR also have a `CHANGELOG.md` update creating this `0.2.0` section and a new `[unreleased]` section?

**Comment by ktangsali** [comment]
@akshaysubr good catch, just updated it

**Review by NickGeneva — APPROVED** [review]

**Review by mnabian — APPROVED** [review]

**Pull request merged**
