### PR TITLE
Enh ext sfno update

### PR DESCRIPTION
**Pull request by daviddpruitt**
# Modulus Pull Request

## Description
Update to SFNO model

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is
up to date with these changes.

## Dependencies

No dependencies

### CODE REVIEW

**Comment by mnabian** [comment]
Thanks @daviddpruitt for the PR! Could you please update the changelog?

**Review by mnabian — APPROVED** [review]
LGTM

**Review by loliverhennigh — APPROVED** [review]

**Pull request merged**
